name: release
on:
  workflow_dispatch:
  push:
    tags: ['v*']
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build binaries
        run: |
          set -eux
          mkdir -p dist
          for pair in "windows/amd64" "linux/amd64" "darwin/amd64" "darwin/arm64"; do
            GOOS="${pair%/*}"
            GOARCH="${pair#*/}"
            OUT="idlenet-${GOOS}-${GOARCH}"
            if [ "$GOOS" = "windows" ]; then OUT="${OUT}.exe"; fi
            GOOS=$GOOS GOARCH=$GOARCH CGO_ENABLED=0 go build -o "dist/${OUT}" ./cmd/idlenet
          done
          (cd dist && sha256sum * > SHA256SUMS.txt || shasum -a 256 * > SHA256SUMS.txt)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: dist/*
