name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v0.2.0)"
        required: true
        default: v0.2.0

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: windows
            goarch: amd64
            outfile: idlenet-windows-amd64.exe
          - goos: darwin
            goarch: arm64
            outfile: idlenet-darwin-arm64
          - goos: darwin
            goarch: amd64
            outfile: idlenet-darwin-amd64
          - goos: linux
            goarch: amd64
            outfile: idlenet-linux-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Tidy & download deps
        run: |
          go mod tidy
          go mod download

      - name: Build ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          CGO_ENABLED: 0
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -trimpath -ldflags "-s -w" -o "${{ matrix.outfile }}" ./cmd/idlenet
          ls -l

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.outfile }}
          path: ${{ matrix.outfile }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Create checksums
        working-directory: dist
        run: |
          sha256sum idlenet-* > SHA256SUMS.txt
          ls -l

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            dist/idlenet-*
            dist/SHA256SUMS.txt
          draft: false
          prerelease: false
